### PR TITLE
Object pools

### PR DESCRIPTION
**Pull request by direvius**
Baseline:
BenchmarkJsonDecoder-4	  500000	      2959 ns/op
BenchmarkJsonDecoder-4	  500000	      2976 ns/op
BenchmarkJsonDecoder-4	  500000	      2971 ns/op

### CODE REVIEW

**Comment by direvius** [comment]
There's too big variance from test to test with default benchmark settings. Trying with -benchtime 30s:
```
# w/o pooling
BenchmarkJsonDecoder-4	20000000	      3078 ns/op
BenchmarkJsonDecoder-4	20000000	      3009 ns/op
# with pooling
BenchmarkJsonDecoder-4	20000000	      3018 ns/op
BenchmarkJsonDecoder-4	20000000	      2959 ns/op
```

**Comment by direvius** [comment]
Without pooling:
```
  50143 1452684742
  49955 1452684743
  48331 1452684744
  50138 1452684745
  49493 1452684746
  49348 1452684747
```
With pooling:
```
  52029 1452685580
  52486 1452685581
  50379 1452685582
  50505 1452685583
  51528 1452685584
  49954 1452685585
  50689 1452685586
  49643 1452685587
```

**Comment by direvius** [comment]
With byte buffer:
```
51298 1452696094
  52349 1452696095
  51420 1452696096
  51969 1452696097
  52074 1452696098
  51280 1452696099
```

**Comment by direvius** [comment]
+2.16% free memory. Almost no difference in RPS.

**Comment by m0sth8** [comment]
:+1:

**Pull request merged**
